#!/usr/bin/env ruby

puts "Script loading..."

Pusher.app_id = '20370'
Pusher.key = 'c65375e6d64ae2e5ba40'
Pusher.secret = '0df645eb0ab088349896'

begin
  REDIS.subscribe('conversion_load_time_range_channel') do |on|
    on.subscribe do |channel, subscriptions_count|
      puts "Subscribed to ##{channel} (#{subscriptions_count} subscriptions)"
    end

    on.message do |channel, message|
      puts "Message: #{channel} #{message}"
      message = JSON.parse(message)
      max_category = 0
      categories = []
      total = []
      converted = []

      message[0].each_slice(2) do |x, y|
        max_category = x if x > max_category
      end

      i = 0
      while i <= max_category do
        categories << i
        total << 0
        converted << 0
        i += 0.5
      end

      message[0].each_slice(2) do |x, y|
        category_index = categories.index(x)
        total[category_index] = y
      end

      converted_total = 0
      message[1].each_slice(2) do |x, y|
        category_index = categories.index(x)
        converted[category_index] = y
        converted_total += y
      end

      converted.collect! { |value| 1.0 * value / converted_total * 100 }

      categories.each_with_index do |value, index|
        categories[index] = value.to_s + ' - ' + (value+0.5).to_s
      end

      
      Pusher[channel].trigger('conversion_range_load_time_event', {:data => {categories: categories, total: total, converted: converted} }.to_json)
    end

    on.unsubscribe do |channel, subscriptions_count|
     puts "Unsubscribed for ##{channel} (#{total} subscriptions)"
    end
  end
rescue Interrupt
  puts 'bye'
end